I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 1387, in script
    if not game_state["chapter_1"]["projector_room"]["viewed_tutorial"]:
  File "game/script.rpy", line 1387, in <module>
    if not game_state["chapter_1"]["projector_room"]["viewed_tutorial"]:
KeyError: 'viewed_tutorial'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 1387, in script
    if not game_state["chapter_1"]["projector_room"]["viewed_tutorial"]:
  File "D:\renpy\renpy-8.0.1-sdk\renpy\ast.py", line 1842, in execute
    if renpy.python.py_eval(condition):
  File "D:\renpy\renpy-8.0.1-sdk\renpy\python.py", line 1209, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\renpy\renpy-8.0.1-sdk\renpy\python.py", line 1202, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/script.rpy", line 1387, in <module>
    if not game_state["chapter_1"]["projector_room"]["viewed_tutorial"]:
KeyError: 'viewed_tutorial'

Windows-10-10.0.26100 AMD64
Ren'Py 8.2.1.24030407
The Merge 1.0
Mon Jul 14 12:03:06 2025
