I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 69, in script
    $ renpy.pause(0.1, hard=True)
Exception: Possible infinite loop.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 69, in script
    $ renpy.pause(0.1, hard=True)
  File "D:\renpy\renpy-8.0.1-sdk\renpy\execution.py", line 61, in check_infinite_loop
    raise Exception("Possible infinite loop.")
Exception: Possible infinite loop.

Windows-10-10.0.26100 AMD64
Ren'Py 8.2.1.24030407
The Merge 1.0
Tue Jul  8 00:02:11 2025
